% 2.12
> setwd("C:/Users/shuimiantiancai/Desktop/IR")
> df1<-read.table("m-aaa.txt", header=FALSE)
> SeriesAAA<-ts(df1$V4)
> df2<-read.table("m-baa.txt", header=FALSE)
> SeriesBAA<-ts(df2$V4)
> diff_AAA<-diff(SeriesAAA)
> diff_BAA<-diff(SeriesBAA)
> MyTable<-rbind(diff_AAA, diff_BAA)
> typeof(MyTable)
> MyTable<-t(MyTable)
> MyTable<-as.data.frame(MyTable)
> LinearModel<-lm(diff_AAA~diff_BAA,data=MyTable)
> summary(LinearModel)
> Residuals<-residuals(LinearModel)
> Acf(Residuals)
> airline<-Arima(Residuals,order=c(2,0,1), seasonal=list(c(1,0,1),period=4))
> summary(airline)
> ResidualsInAirline<-residuals(airline)
> Acf(ResidualsInAirline)
> Box.test(ResidualsInAirline,lag=20,type=c("Ljung-Box"))
% 残差序列进行ARMA拟合后其残差仍有序列相关，不过到此为止，不再复杂化了。
