% 2.15
> df<-read.table("q-gdpdef.txt",header=FALSE)
> Series<-ts(df$V3)
> Acf(Series)
> diff_Series<-diff(Series)
> Acf(diff_Series)
> diff2_Series<-diff(diff_Series)
> Acf(diff2_Series)
> Acf(diff2_Series,lag.max = 50)
> Pacf(diff2_Series,lag.max = 50)
> MyAirline<-Arima(Series, order=c(3,2,1))
> summary(MyAirline)
> MyRes<-residuals(MyAirline)
> Acf(MyRes)
> Box.test(MyRes, lag=20, type=c("Ljung-Box"))
