% 2.6
> df<-read.table("power6.txt",header=FALSE)
> Myseries<-ts(df$V1)
> typeof(Myseries)
> Acf(Myseries)
> diff_Myseries<-diff(Myseries)
> Acf(diff_Myseries)
> airline_model<-Arima(Myseries,order=c(2,1,1), seasonal = list(order=c(1,1,1), period=12))
> Myresiduals<-residuals(airline_model)
> Acf(Myresiduals)
> Box.test(Myresiduals, lag=20, type="Ljung-Box")
> summary(airline_model)
> MyForecast<-forecast(airline_model,h=24)
> summary(MyForecast)
