% 2.4
setwd("C:/Users/shuimiantiancai/Desktop/IR")
df<-read.table("m-decile1510.txt", header=FALSE)
View(df)
series1<-ts(df$V2)
Acf(series1)
series2<-ts(df$V3)
Acf(series2)
series3<-ts(df$V4)
Acf(series3)

> Acf(series2)
> Pacf(series2)
> AR_Model_Decile5<-Arima(series2,order=c(1,1,0), include.constant = TRUE)
> summary(AR_Model_Decile5)
> AR_forecast<-forecast(AR_Model_Decile5,h=3)
> summary(AR_forecast)
> MA_Model_Decile5<-Arima(series2,order=c(0,1,1), include.constant = TRUE)
> MA_forecast<-forecast(MA_Model_Decile5,h=3)
> summary(MA_forecast)
